[tool.poetry]
name = "health-app"
version = "0.1.0"
description = ""
authors = ["mdoktor7 <mdoktor696@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
